services:
  email-parser:
    build: .
    container_name: email_parser
    restart: always
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
